name: Hourly Regional Weather Fetch & Deploy

on:
  schedule:
    # 분 시 일 월 요일
    # 매시간 0분에 실행 (UTC 기준, 한국 시간 매시 정각)
    - cron: '0 * * * *'
  workflow_dispatch: # 수동 테스트용 버튼 활성화

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        #cache: 'pip'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests
        pip install firebase-admin
    - name: Create Firebase Service Account JSON
      run: |
        # GitHub Secrets에 숨겨둔 암호문 문자열을 읽어서 임시 파일로 저장합니다.
        echo "${{ secrets.FIREBASE_SERVICE_ACCOUNT_JSON }}" > firebase_service_account.json

    - name: Run Weather Fetch Script
      run: python fetch_weather.py

    - name: Clean up Credentials
      if: always() # 스크립트가 성공하든 실패하든 무조건 실행
      run: |
        # 가상 머신이 종료되기 전에 혹시 모를 흔적을 지우기 위해 비밀키 파일을 삭제합니다.
        rm -f firebase_service_account.json

    - name: Run Weather Fetch Script
      run: python counter.py

    - name: Deploy to Firebase Hosting
      uses: FirebaseExtended/action-hosting-deploy@v0
      with:
        repoToken: '${{ secrets.GITHUB_TOKEN }}'
        firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_JSON }}'
        projectId: test-b30a4 # ⚠️ 본인의 Firebase 프로젝트 ID로 변경 필수
        channelId: live